### ISSUE TITLE
Distilling throws error since v2.0.1

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/django-mapengine#23]
Distilling now throws:
AttributeError: 'Settings' object has no attribute 'MAP_ENGINE_ZOOM_LEVELS'

**Comment by henhuy** [comment]
Can't reproduce your error?! On my side, distilling works via `export DJANGO_READ_DOT_ENV_FILE=True; make distill` with any error.

**Comment by nesnoj** [comment]
Resolved
