### ISSUE TITLE
Hide choropleth legend

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/django-mapengine#8]
Apparently, there's no feature to hide the choropleth legend, right?
Does it make sense to add a corresponding event & function to the mapengine or do you recommend to add this to the app which uses the mapengine? (DP, in my case, https://github.com/rl-institut/digiplan/issues/390)
@henhuy

**Comment by henhuy** [comment]
Yes, it makes sense to add this functionality in django-mapengine! 
Thanks for pointing out.

**Comment by nesnoj** [comment]
> Yes, it makes sense to add this functionality in django-mapengine! Thanks for pointing out.

Thx, I'll give it a try..

**Comment by nesnoj** [comment]
Closed via #9
